### PR TITLE
Graph Visualization

### PR DESCRIPTION
**Pull request by yigitozkavci**
Related issue: https://github.com/well-typed/visualize-cbn/issues/2

This PR adds the capability of graph visualization to the existing textual and javascript output options.

- Dot language is being used for representing graphs
- We do not provide PDF or PNG format for graphs, but instead, create the `.dot` file. This it because `graphviz` library is heavyweight for our needs.

I tried every file in `examples/` directory, and all of them worked as expected. I put the output of `examples/head-map-repeat.hs` here for convenience:

head-map-repeat

### CODE REVIEW

**Comment by edsko** [comment]
Ooooh very cool! I'll try to make some time this week to look at this PR (and the other open PR that I still haven't had a time to look at :flushed: ). Good stuff!

**Comment by edsko** [comment]
Sorry for the slow reply, it's been very hectic. Unfortunately I will be out of the country for a few weeks now. I _will_ take a look at this when I get back! :)

**Comment by yigitozkavci** [comment]
No worries, in the meantime I'll try to work on other possible improvements, since I loved the project :)

**Comment by edsko** [comment]
I've squashed your commits and merged into master, will release soon. Thanks for the PR, and sorry for the very slow response time. I so rarely get a chance to work on this project :) 

By the way, I'm curious, why did you introduce dotty output? Did/do you envision an evaluation function where the evaluation graph isn't linear, or do you just find the dotty output convenient for rendering?

**Comment by yigitozkavci** [comment]
No, I didn't think graphs would be non-linear, that would mean there are multiple ways of reducing an expression, I don't think that's the case with this language.

I had experience with `dot` language and I do find it very convenient to represent directed graphs with, even though it looks uglier than html output. This is the main reason :)

**Pull request closed without merging**
